---
# Basic ec2 provisioning example
- hosts: localhost
  gather_facts: False
  tasks:
  - name: Create Ec2 Instance
    local_action:
      module: ec2
      instance_type: "{{instance_type}}"
      region: "{{aws_region}}"
      image: "{{ami_id}}"
      wait: yes
      group: webserver
      count: 1
      #vpc_subnet_id: "{{subnet_id}}"
      assign_public_ip: yes
