---
- name: Try out any module
  hosts: localhost
  connection: local

  environment:
    PYTHONPATH: "/usr/local/lib/python2.7/site-packages:$PYTHONPATH"
  gather_facts: False
  roles:
  - ansible_manageiq
  - ansible_manageiq_modules

  tasks:
    #- import_tasks: tasks/manageiq_user.yml
  - import_tasks: tasks/manageiq_automate.yml
