---
- name: Try out any module
  hosts: localhost
  connection: local

  environment:
    PYTHONPATH: "/usr/local/lib/python2.7/site-packages:$PYTHONPATH"
  gather_facts: False
  roles:
  - ansible_manageiq
  - ansible_manageiq_modules

  tasks:
    #- import_tasks: tasks/manageiq_user.yml
  - import_tasks: tasks/manageiq_automate.yml

  post_tasks:
    - name: "Run the post tasks"
      debug: msg="Committing the workspace"
      changed_when: true
      notify: "Commit the Workspace"
