---
- name: Try out any module
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
  - ansible_manageiq_modules
  tasks:
    #- debug: var=manageiq

  - name: "ManageIQ API Passthrough"
    ansible_manageiq_api:
      state: 'get'
      miq_url: 'http://localhost:3000'
      miq_username: 'admin'
      miq_password: 'smartvm'
      miq_verify_ssl: False
      endpoint: 'vms'
    tags: api_one

  - name: "ManageIQ API Passthrough Token"
    ansible_manageiq_api:
      state: 'get'
      miq_username: 'admin'
      miq_password: 'smartvm'
      endpoint: 'hosts'
    tags: api

  - name: "Complete Dummy Test Module"
    test:
    tags: test
