---
- name: Try out any module
  hosts: Home
  #hosts: localhost
  #connection: local
  gather_facts: True

  roles:
  - ansible_manageiq_modules
  - ansible_manageiq

  environment:
    MIQ_TOKEN: "6eeec7c59500edfbf0bbbcee8cf040f5"
    MIQ_URL: "http://10.0.1.36:3000"
    PYTHONPATH: "/private/var/folders/mf/4ystcct14jn_4j832jwvp0xh0000gn/T/src/manageiq-client/src:/usr/local/lib/python2.7/site-packages:$PYTHONPATH"

  tasks:
  - name: "ManageIQ API Passthrough"
    ansible_manageiq_api:
      state: 'get'
      miq_url: 'http://10.0.1.36:3000'
      miq_username: 'admin'
      miq_password: 'smartvm'
      miq_verify_ssl: False
      endpoint: 'hosts'
    tags: api_one

  - name: "ManageIQ API Passthrough Token"
    ansible_manageiq_api:
      state: 'get'
      endpoint: 'hosts'
    tags: api

  - name: "Complete Dummy Test Module"
    test:
    tags: test
