---
- name: Try out any module
  hosts: Home
  #hosts: localhost
  #connection: local
  gather_facts: False
  roles:
  - ansible_manageiq_modules
    #- ansible_manageiq
  tasks:
    #- debug: var=manageiq

  - name: "ManageIQ API Passthrough"
    ansible_manageiq_api:
      state: 'get'
      miq_url: 'http://10.0.1.36:3000'
      miq_username: 'admin'
      miq_password: 'smartvm'
      miq_verify_ssl: False
      endpoint: 'hosts'
    environment:
      PYTHONPATH: "./roles/ansible_manageiq_modules/library"
    tags: api

  - name: "ManageIQ API Passthrough Token"
    ansible_manageiq_api:
      state: 'get'
      miq_username: 'admin'
      miq_password: 'smartvm'
      endpoint: 'hosts'
    environment:
      PYTHONPATH: "./roles/ansible_manageiq_modules/library"
    tags: api_one

  - name: "Complete Dummy Test Module"
    test:
    tags: test
