---
- hosts: staging
  gather_facts: False
  vars:
    branch: 'develop'

  tasks:
  - name: "Grab the latest from branch: {{ branch | default('develop') }}"
    git:
      repo: "git@github.com:syncrou/onramp.git" 
      dest: "/home/centuryd/onramp/current" 
      version: "{{ branch | default('develop') }}"
      update: yes
      force: yes
    tags:
      git

  - name: "Migrate the Database"
    shell: "cd /home/centuryd/onramp/current && RAILS_ENV=frt_prod rake db:migrate"
    register: migrate
    tags:
      db

  - debug: var=migrate.stdout

  - name: "Restart all monit services"
    monit:
      name: "{{ item }}"
      state: restarted
    with_items:
      - unicorn_onramp_master
      - unicorn_worker_0
      - unicorn_worker_1
      - unicorn_worker_2
      - unicorn_worker_3
      - resque_worker_1
    become: true
    tags:
      monit
