---
- hosts: staging
  gather_facts: False
  vars:
    branch: 'develop'
    monit_name: 'unicorn_onramp_master'

  tasks:
  - name: "Grab the latest from branch: {{ branch | default('develop') }}"
    git:
      repo: "git@github.com:syncrou/onramp.git" 
      dest: "/home/centuryd/onramp/current" 
      version: "{{ branch | default('develop') }}"
      update: yes
      force: yes
    tags:
      git

  - name: "Restart all monit services"
    monit:
      name: "{{ monit_name }}"
      state: restarted
    become: true
    tags:
      monit
