---
# Dump a db to a file, save up to 4 versions of that file on the remote system
#   Fetch the file and save it on the local system (Dropbox)
#   Save 2 versions on the local system.
- hosts: prod
  gather_facts: False
  tasks:
  - name: Pull in the db vars
    include_vars:
      file: secrets.yml
      name: secret
  - set_fact: mydate="{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
  - debug: var=mydate
  - name: Dump the {{ secret.db_name }} database to {{ secret.db_name }}_{{ mydate }}.sql
    mysql_db:
      login_user: "{{ secret.user }}"
      login_password: "{{ secret.password }}"
      login_host: "{{ secret.host }}"
      state: dump
      name: "{{ secret.db_name }}"
      target: "{{ secret.remote_folder }}{{ secret.db_name }}_{{ mydate }}.sql"

  - name: Only keep the 4 newest database dump files
    raw: "cd {{ secret.remote_folder }} && ls -tp | grep -v '/$' | tail -n +5 | xargs -d '\n' rm --"

  - name: Fetch the database file and dump it into Dropbox
    fetch:
      src: "{{ secret.remote_folder }}onramp_{{ mydate }}.sql"
      dest: "{{ secret.local_folder }}"

- hosts: localhost
  gather_facts: False
  tasks:
  - name: Localhost changes
    include_vars:
      file: secrets.yml
      name: secret
  - name: Only keep the 2 newest files on Dropbox
    raw: "cd {{ secret.local_folder_combined }} && ls -tp | grep -v '/$' | tail -n +3 | gxargs -d '\n' rm --"
