---
# Ec2 start
- name: 
  hosts: localhost
  connection: local
  gather_facts: False
    tasks:
    - name: Start the sandbox instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: running
        wait: True
        vpc_subnet_id: '{{ subnet_id }}'
        assign_public_ip: yes
