---
- hosts: localhost
  gather_facts: False
  tasks:
  - name: Pull in the db vars
    include_vars:
      file: secrets_update.yml
      name: secret
    tags:
      config

  - name: Grab the newest db dump file
    shell: "cd {{ secret.local_folder_combined }} && ls -Art | tail -n 1"
    register: sql_file
    tags: config

  - debug: var=sql_file.stdout
    tags: config

  - name: "Update {{ secret.db_name }} database with the latest db file"
    mysql_db:
      login_user: "{{ secret.user }}"
      login_password: "{{ secret.password }}"
      login_host: "{{ secret.host }}"
      state: import
      name: "{{ secret.db_name }}"
      target: "{{ secret.local_folder_combined }}/{{ sql_file.stdout }}"
    tags:
      mysql
