---
- name: "Get an attribute"
  manageiq_automate:
    workspace: "{{ workspace }}"
    get_attribute:
      object: "/ManageIQ/System/Request/call_instance"
      attribute: "::miq::parent"

- name: "Set an attribute"
  manageiq_automate:
    workspace: "{{ workspace }}"
    set_attribute:
      object: "root"
      attribute: "my_name"
      value:  "Freda"
  register: workspace
