---
- name: "ManageIQ Grab the Workspace"
  manageiq_automate_workspace:
    guid: 'ea349415-d672-4c89-818c-48b3782c24a4'
    get_workspace:
    manageiq_connection:
      url: 'http://localhost:3000'
      username: 'admin'
      password: 'smartvm'
      verify_ssl: False
  register: workspace
  tags: workspace_tag

- name: "Set an attribute"
  manageiq_automate_workspace:
    set_attribute:
      target: "{{ workspace.object }}"
      root:
        my_name: "drew"
  register: workspace
  tags: workspace_tag

- name: "ManageIQ fetch vmdb object"
  manageiq_automate_workspace:
    vmdb_object:
      target: "{{ workspace.object }}"
      root:
        attribute_name: "vm"
  register: vm
  tags: workspace_tag

- name: "ManageIQ vm start"
  manageiq_automate_workspace:
    guid: 'ea349415-d672-4c89-818c-48b3782c24a4'
    start_vm: "{{ vm }}"
    manageiq_connection:
      url: 'http://localhost:3000'
      username: 'admin'
      password: 'smartvm'
      verify_ssl: False
  tags: workspace_tag

- name: "ManageIQ vm custom attributes"
  manageiq_automate_workspace:
    guid: 'ea349415-d672-4c89-818c-48b3782c24a4'
    add_attributes:
      vm: "{{ vm }}"
      custom_attributes:
        ip_address: '12.34.23.54'
    manageiq_connection:
      url: 'http://localhost:3000'
      username: 'admin'
      password: 'smartvm'
      verify_ssl: False
  tags: workspace_tag
