---
- name: "ManageIQ Modify Automate Workspace"
  manageiq_automate_workspace:
    guid: 'ea349415-d672-4c89-818c-48b3782c24a4'
    workspace:
      set_attribute:
        root:
          my_name: "drew"
    manageiq_connection:
      url: 'http://localhost:3000'
      username: 'admin'
      password: 'smartvm'
      verify_ssl: False
  tags: user

- name: "ManageIQ getAttribute"
  manageiq_automate_workspace:
    guid: 'ea349415-d672-4c89-818c-48b3782c24a4'
    fetch_vmdb_object:
      root:
        whichvm: "vmdb_reference::vms/192"
    manageiq_connection:
      url: 'http://localhost:3000'
      username: 'admin'
      password: 'smartvm'
      verify_ssl: False
  tags: vm
  #- name: "simpler version"
  #  manageiq_automate_workspace:
  #    workspace_set: "{{ object_based_dictionary }}"
  #
  #- name: "Another task"
  #  manageiq_automate_workspace:
  #    set_retry: 
  #
  #- name: "Get password"
  #  manageiq_automate_workspace:
  #    workspace_decrypt:
  #      root:
  #        attribute:
  #
  #        
  #- name: "Get Vm object"
  #  manageiq_automate_workspace:
  #    fetch_vmdb_object: 
  #      root:
  #        "whichvm":
  #
  ## "whichvm": "vmdb_reference::vms/192",
  #- name: "Get Vm object 2"
  #  manageiq_automate_workspace:
  #    workspace_get: 
  #      root:
  #        "whichvm": 
  #
  ## "name": "drew",
  #- name: "Get name from the root object"
  #  manageiq_automate_workspace:
  #    workspace_get: 
  #      root:
  #        name: 
  #        #
  ## "ipam_password": "miq_password::{ AES256 }23434234234",
  ## Returns decrypted value from vmdb REST API
  #- name: "Get password from root object"
  #  manageiq_automate_workspace:
  #    workspace_get: 
  #      root:
  #        ipam_password: 
