---
- name: "Install the python api client outside of the virtual environment"
  pip:
    name: "{{ item }}"
    state: latest
    executable: /usr/local/bin/pip
  with_items:
    - git+https://github.com/syncrou/manageiq-api-client-python.git#egg=manageiq-client
  tags:
    - always
