---
- name: "Install the python api client outside of the virtual environment"
  pip:
    name: "{{ item }}"
    state: forcereinstall
    executable: /usr/local/bin/pip
  with_items:
    - git+https://github.com/syncrou/manageiq-api-client-python.git#egg=manageiq_client
    - requests
  tags:
    - always
