---
- name: "Install Required Modules"
  pip:
    name: "{{ item }}"
    executable: /usr/local/bin/pip
  loop:
    - git+https://github.com/syncrou/manageiq-api-client-python.git#egg=manageiq_client
    - requests
    - dpath

- name: "Get the Workspace"
  manageiq_automate:
    get_workspace: yes
  register: workspace
