---
- hosts: staging
  gather_facts: False

  environment:
    GEM_PATH: /home/centuryd/.gem/ruby/2.0.0

  tasks:
  - name: "Grab the latest from branch: {{ branch | default('develop') }}"
    git:
      repo: "{{ repo }}"
      dest: "{{ destination }}"
      version: "{{ branch | default('develop') }}"
      update: yes
      force: yes
    tags:
      git

  - name: "Migrate the Database"
    shell: "cd {{ destination }} && RAILS_ENV={{ env }} rake db:migrate"
    register: migrate
    tags:
      db

  - debug: var=migrate.stdout

  - name: "Restart all monit services"
    monit:
      name: "{{ item }}"
      state: restarted
    with_items: "{{ monit }}"
    become: true
    tags:
      monit
