---
- hosts: staging
  gather_facts: False

  tasks:
  - name: Pull in the vars file
    include_vars:
      file: deploy_staging_vars.yml
      name: deploy_staging
  - name: "Grab the latest from branch: {{ deploy_staging.branch | default('develop') }}"
    git:
      repo: "git@github.com:syncrou/onramp.git" 
      dest: "/home/centuryd/onramp/current" 
      version: "{{ deploy_staging.branch | default('develop') }}"
      update: yes
      force: yes
    tags:
      git

  - name: "Migrate the Database"
    shell: "cd /home/centuryd/onramp/current && RAILS_ENV=frt_prod rake db:migrate"
    register: migrate
    tags:
      db

  - debug: var=migrate.stdout

  - name: "Restart all monit services"
    monit:
      name: "{{ item }}"
      state: restarted
    with_items: "{{ deploy_staging.monit }}"
    become: true
    tags:
      monit
