---
- hosts: staging
  gather_facts: False

  environment:
    GEM_PATH: /home/centuryd/.gem/ruby/2.0.0:/home/centuryd/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0
    PATH: "{{ path }}"

  tasks:
  - name: "Grab the latest from branch: {{ branch | default('develop') }}"
    git:
      repo: "{{ repo }}"
      dest: "{{ destination }}"
      version: "{{ branch | default('develop') }}"
      update: yes
      force: yes
    tags:
      git

  - name: "Migrate the Database"
    shell: "cd {{ destination }} && RAILS_ENV={{ env }} rake db:migrate"
    register: migrate
    tags:
      db

  - debug: var=migrate.stdout

  - name: "Restart all monit services"
    raw: "monit restart all"
    become: true
    tags:
      monit
