---
- hosts: staging
  gather_facts: False

  tasks:
  - name: Grab the newest db dump file
    shell: "cd {{ local_folder_combined }} && ls -Art | tail -n 1"
    register: sql_file
    tags: 
      config

  - debug: var=sql_file.stdout

  - name: "Update {{ db_name }} database with the latest db file"
    mysql_db:
      login_user: "{{ user }}"
      login_password: "{{ password }}"
      login_host: "{{ host }}"
      state: import
      name: "{{ db_name }}"
      target: "{{ local_folder_combined }}/{{ sql_file.stdout }}"
    tags:
      mysql
