---
- name: Service Linking VM's to an existing service
  hosts: localhost
  connection: local
  vars:

  gather_facts: False
  roles:
  - manageiq_vmdb

  tasks:
    - name: Service Linking via an href slug
      manageiq_vmdb:
        vmdb: "href_slug::services/80"
        action: add_provider_vms
        data:
          uid_ems:
            - vm1-234234234
            - vm2-ada987987
            - vm3-324lkjsdf
          provider:
            id: 15

    - name: Service Linking via and endpoint
      manageiq_vmdb:
        vmdb: "services/80"
        action: add_provider_vms
        data:
          uid_ems:
            - vm1-sdfsdf908
            - vm2-234lkj
            - vm3-987dfs23
          provider:
            id: 15
