---
- name: Siphon Method Parameters into an object
  hosts: localhost
  connection: local
  vars:

  gather_facts: False
  roles:
  - manageiq_vmdb

  tasks:
    - name: Service Linking
      manageiq_vmdb:
        href: "services/80"
        action: add_provider_vms
        data: 
          vms: 
            - vm1
            - vm2
            - vm3
          provider: 1223

    - name: Get vmdb_object
      manageiq_vmdb:
        get_vmdb_object:
        href: "services/80"
      register: vmdb_object

    - name: Service Linking
      manageiq_vmdb:
        vmdb: "{{ vmdb_object }}"
        action: add_provider_vms
        data: 
          vms: 
            - vm1
            - vm2
            - vm3
          provider: 1223

    - name: Get vmdb_object
      manageiq_vmdb:
        get_vmdb_object:
        href: "https://localhost:3000/api/services/80"
      register: vmdb_object
