---
- name: Service Linking
  hosts: localhost
  connection: local

  gather_facts: False
  roles:
  - manageiq_vmdb

  pre_tasks:
    - name: "Run the pre tasks"
      debug: msg="Getting the workspace"
      changed_when: true
      notify: "Get the Workspace"

  tasks:
    #- import_tasks: tasks/manageiq_user.yml
  - import_tasks: tasks/manageiq_automate.yml

  post_tasks:
    - name: "Run the post tasks"
      debug: msg="Committing the workspace"
      changed_when: true
      notify: "Commit the Workspace"
