---
- hosts: all
  gather_facts: false
  sudo: yes
  tasks:
  # Upgrade all packages to the latest
  - name: upgrade all packages
    yum: name=* state=latest

  # Install http ruby etc
  - name: Install http and ruby etc
    yum: name={{ item }} state=present
    with_items:
    - httpd
    - ruby
    - git
    
  # Enable the http service
  - name: http service state
    service: name=httpd state=started enabled=yes
